import { TitleCasePipe } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  imports: [TitleCasePipe],
  selector: 'app-manage-users',
  styleUrl: './manage-users.css',
  templateUrl: './manage-users.html',
})
export class ManageUsers {
  columns: string[] = ['id', 'name', 'email', 'phone', 'role', 'status'];

  users: any = [{
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "admin",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "admin",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "admin",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "admin",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "admin",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  }, {
    id: 1,
    name: "esraa",
    email: "dddddddddd",
    phone: "1111111111",
    role: "user",
    status: "active"
  },]
}
